name: parking_lot
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  js: ^0.6.2
  equatable: ^1.2.5
  sprintf: "^4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1
  build_runner: ^1.10.1